name: Gas Town MEOW Stack - Production Deployment

on:
  push:
    branches: [ main, master, production ]
  pull_request:
    branches: [ main, master, production ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'

env:
  PROJECT_NAME: gas-town-meow-stack
  PYTHON_VERSION: '3.12'

jobs:
  validate:
    name: Validation and Security
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bandit safety black flake8 pytest
    
    - name: Security scan
      run: |
        echo "Running security scans..."
        bandit -r . -f json -o security-report.json || true
        safety check --json --output safety-report.json || true
    
    - name: Code quality check
      run: |
        echo "Running code quality checks..."
        black --check . || echo "Code formatting issues found"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Deployment readiness check
      run: |
        echo "Checking deployment readiness..."
        required_files=(
          "requirements.txt"
          "setup_marketplace.py" 
          "deployment/scripts/deploy/deploy_meow_stack.sh"
          "deployment/scripts/rollback/rollback_meow_stack.sh"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Required file missing: $file"
            exit 1
          fi
        done

  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        echo "Running test suite..."
        if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
          pytest --cov=. --cov-report=xml
        else
          echo "No test files found"
        fi

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [validate, test]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup deployment environment
      run: |
        echo "Setting up production deployment environment..."
        sudo apt-get update
        sudo apt-get install -y sqlite3 curl jq
        chmod +x deployment/scripts/deploy/deploy_meow_stack.sh
        chmod +x deployment/scripts/rollback/rollback_meow_stack.sh
        chmod +x deployment/scripts/zero-downtime/blue_green_deploy.sh
    
    - name: Pre-deployment validation
      run: |
        echo "Running pre-deployment validation..."
        bash deployment/scripts/deploy/deploy_meow_stack.sh --validate-only
    
    - name: Execute blue-green deployment
      run: |
        echo "Executing production deployment..."
        bash deployment/scripts/zero-downtime/blue_green_deploy.sh
    
    - name: Post-deployment health check
      run: |
        echo "Running post-deployment health check..."
        sleep 30
        if [ -x "monitoring/scripts/health_check.sh" ]; then
          cd monitoring
          timeout 300 bash scripts/health_check.sh || (cd .. && bash deployment/scripts/rollback/rollback_meow_stack.sh --force)
        fi
